language: objective-c
osx_image: xcode7
script:
    - xctool -scheme 'TypedKey-iOS' -sdk iphonesimulator CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO test -parallelize
    - xctool -scheme 'TypedKey-OSX' test -parallelize
